version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - rnwa-net
  php:
    image: petekaik/php-fpm-mysqli
    volumes:
      - ./:/code
    networks:
      - rnwa-net
networks:
  rnwa-net:
    external:
      name: rnwa-net
